### ISSUE TITLE
JSON is implementation detail of multilang and shouldn't be surfaced into components

### ISSUE THREAD

**Issue by et1975** [fwaris/FsStorm#3]
I'd like to be able to specify the type I emit and expect (per stream) and let FsStorm to serialize the tuples in and out of JSON.

**Comment by fwaris** [comment]
Whenever I have needed strong typing, I have done a simple mapping from json to record. 
For example:
let tuple = msg?(Storm.TUPLE).Array
{Key1=tuple.[0].Val; Key2=tuple.[1].ValF...}

The reverse can be done with FsJson constructors (jval etc.)

Here is some documentation on FsJson: https://fwaris.wordpress.com/2012/06/09/fsjson/

We would need a layer above FsStorm to accomplish auto-serialization plus will have to replace FsJson with Json.NET or equivalent ( FsJson is meant to work with loose json documents).

This probably requires a complete re-write. If we are to re-write, I think a better effort would be to abstract a lot more and base the whole thing on computation expressions with Rx underpinnings. 

I consider this version as a learning exercise.

**Comment by et1975** [comment]
Please see https://groups.google.com/forum/#!topic/storm-user/9aeJr9dhesA
and https://github.com/jsgilmore/protoshell

This is not about strong/weak typing, this issue is about separation of concerns: protocol impl vs higher level logic that uses it.
