### ISSUE TITLE
Support for emitting bolts

### ISSUE THREAD

**Issue by et1975** [fwaris/FsStorm#4]
I should be able to emit from the bolts with out-of-the-box FsStorm abstractions.

**Comment by et1975** [comment]
- related anchor support

**Comment by fwaris** [comment]
Bolts can emit using FsStorm.emit as in:
    let msg = jval [Storm.TUPLE, ["key1", jval val1; "key2", jval val2]]
    emit msg

I have been using intermediate bolts at work but have not needed to add anchors yet.

I agree a version of emit that also performs anchoring would be helpful. For now you can construct the emitted message manually with anchors using the FsJson constructors (jval and others). For example:    

let msg = 
   jval [
            Storm.TUPLE, ["key1", jval val1; "key2", jval val2]
            "anchors", [jval id1; jval id2]
    ]
emit msg

**Comment by et1975** [comment]
I've added a few of functions in my fork: tuple, anchor, namedStream.
Closing.
