### ISSUE TITLE
StormSubmit script assumes the same OS for the server as for the client

### ISSUE THREAD

**Issue by et1975** [fwaris/FsStorm#6]
I should be able to submit a topology from a Windows machine to a Linux-hosted storm.
Currently isMono() test results end up misleading the server about the executable path.

**Comment by fwaris** [comment]
By design the main function is not fully specified because flexibility is needed and I don't know all the possible scenarios that could be encountered.

At work I have been modifying main function as needed. The isMono() helper function is just for convenience - it can be ignored.
